### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by raghunandy** [Meabed/nutch-cassandra-docker#2]
My build was successful. But following error troubled me. 

./bin/start.sh
./bin/start.sh: 12: ./bin/start.sh: /home/ubuntu/nutch/nutch-cassandra-docker/ipof.sh: not found

**Comment by meabed** [comment]
@visumagic ./bin/start.sh This need to run from the root dir of the project ( look in bin folder ) u will see the ipof.sh 
Try again and let me know

**Comment by raghunandy** [comment]
Yes .. that could be the reason. I checkout again and ran it. I got the following error. I tried to see the start.sh file, but I could not see any mistake ..

docker@boot2docker:~/nutch/nutch-cassandra-docker$ ./bin/start.sh
./bin/start.sh: line 3: syntax error: bad substitution
docker@boot2docker:~/nutch/nutch-cassandra-docker$

Line:
B_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

I could not be able to guess any clue. Please correct me if I am wrong.
