### ISSUE TITLE
Build failing on Ubuntu 16.04 due to dsc21 dependency

### ISSUE THREAD

**Issue by paragjoshi** [Meabed/nutch-cassandra-docker#6]
# I ran "sudo ./bin/sh .build" as per your instructions on Ubuntu 16.04. Docker has been working fine on my system with other dockerfiles. But, on your dockerfile I get this error: 

Step 8 : RUN apt-get install -y dsc21
 ---> Running in 7cdea6b80655
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dsc21 : Depends: cassandra (= 2.1.15) but 3.0.8 is to be installed
# E: Unable to correct problems, you have held broken packages.

How to fix this? 
Thanks

**Comment by normansuesstrunk** [comment]
I've run into the same error and found a solution so the build runs through: 

* OS: Ubuntu 16.04 LTS

```
sudo bin/build.sh
...
The following packages have unmet dependencies:
 dsc21 : Depends: cassandra (= 2.1.15) but 3.0.9 is to be installed
```

Solution adapted from http://stackoverflow.com/questions/26345478/error-installing-datastax-cassandra-2-0

Change cassandra/Dockerfile Line Number 29

from 
```
RUN apt-get install -y dsc21
```

to

```
RUN apt-get install -y dsc21 cassandra=2.1.*
```

Now it builds successfully: 

```
...
Removing intermediate container 6d6bf2e22e3c
Successfully built ee55e9bccc1d
```

**Comment by paragjoshi** [comment]
Norman, thanks for the solution!!

**Comment by meabed** [comment]
Hi Guys,
I am sorry i am super busy, but i will maintain this image with improvements and enhancement next week.

I will convert to docker-compose and docker-machine with better scripts and logging.

**Comment by paragjoshi** [comment]
Meabed, no problem! Thanks a lot for this nice project! :+1:

**Comment by normansuesstrunk** [comment]
@Meabed : thanks alot for the sharing of the project, it helped me alot!
